/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SobreRouteImport } from './routes/sobre'
import { Route as MetodologiaRouteImport } from './routes/metodologia'
import { Route as ContatoRouteImport } from './routes/contato'
import { Route as AppRouteImport } from './routes/app'
import { Route as AcessibilidadeRouteImport } from './routes/acessibilidade'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AppPatotasRouteImport } from './routes/app.patotas'
import { Route as AppMuralRouteImport } from './routes/app.mural'
import { Route as AppMembrosRouteImport } from './routes/app.membros'
import { Route as AppJogosRouteImport } from './routes/app.jogos'

const SobreRoute = SobreRouteImport.update({
  id: '/sobre',
  path: '/sobre',
  getParentRoute: () => rootRouteImport,
} as any)
const MetodologiaRoute = MetodologiaRouteImport.update({
  id: '/metodologia',
  path: '/metodologia',
  getParentRoute: () => rootRouteImport,
} as any)
const ContatoRoute = ContatoRouteImport.update({
  id: '/contato',
  path: '/contato',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const AcessibilidadeRoute = AcessibilidadeRouteImport.update({
  id: '/acessibilidade',
  path: '/acessibilidade',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppPatotasRoute = AppPatotasRouteImport.update({
  id: '/patotas',
  path: '/patotas',
  getParentRoute: () => AppRoute,
} as any)
const AppMuralRoute = AppMuralRouteImport.update({
  id: '/mural',
  path: '/mural',
  getParentRoute: () => AppRoute,
} as any)
const AppMembrosRoute = AppMembrosRouteImport.update({
  id: '/membros',
  path: '/membros',
  getParentRoute: () => AppRoute,
} as any)
const AppJogosRoute = AppJogosRouteImport.update({
  id: '/jogos',
  path: '/jogos',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/acessibilidade': typeof AcessibilidadeRoute
  '/app': typeof AppRouteWithChildren
  '/contato': typeof ContatoRoute
  '/metodologia': typeof MetodologiaRoute
  '/sobre': typeof SobreRoute
  '/app/jogos': typeof AppJogosRoute
  '/app/membros': typeof AppMembrosRoute
  '/app/mural': typeof AppMuralRoute
  '/app/patotas': typeof AppPatotasRoute
  '/app/': typeof AppIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/acessibilidade': typeof AcessibilidadeRoute
  '/contato': typeof ContatoRoute
  '/metodologia': typeof MetodologiaRoute
  '/sobre': typeof SobreRoute
  '/app/jogos': typeof AppJogosRoute
  '/app/membros': typeof AppMembrosRoute
  '/app/mural': typeof AppMuralRoute
  '/app/patotas': typeof AppPatotasRoute
  '/app': typeof AppIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/acessibilidade': typeof AcessibilidadeRoute
  '/app': typeof AppRouteWithChildren
  '/contato': typeof ContatoRoute
  '/metodologia': typeof MetodologiaRoute
  '/sobre': typeof SobreRoute
  '/app/jogos': typeof AppJogosRoute
  '/app/membros': typeof AppMembrosRoute
  '/app/mural': typeof AppMuralRoute
  '/app/patotas': typeof AppPatotasRoute
  '/app/': typeof AppIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/acessibilidade'
    | '/app'
    | '/contato'
    | '/metodologia'
    | '/sobre'
    | '/app/jogos'
    | '/app/membros'
    | '/app/mural'
    | '/app/patotas'
    | '/app/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/acessibilidade'
    | '/contato'
    | '/metodologia'
    | '/sobre'
    | '/app/jogos'
    | '/app/membros'
    | '/app/mural'
    | '/app/patotas'
    | '/app'
  id:
    | '__root__'
    | '/'
    | '/acessibilidade'
    | '/app'
    | '/contato'
    | '/metodologia'
    | '/sobre'
    | '/app/jogos'
    | '/app/membros'
    | '/app/mural'
    | '/app/patotas'
    | '/app/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AcessibilidadeRoute: typeof AcessibilidadeRoute
  AppRoute: typeof AppRouteWithChildren
  ContatoRoute: typeof ContatoRoute
  MetodologiaRoute: typeof MetodologiaRoute
  SobreRoute: typeof SobreRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sobre': {
      id: '/sobre'
      path: '/sobre'
      fullPath: '/sobre'
      preLoaderRoute: typeof SobreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/metodologia': {
      id: '/metodologia'
      path: '/metodologia'
      fullPath: '/metodologia'
      preLoaderRoute: typeof MetodologiaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contato': {
      id: '/contato'
      path: '/contato'
      fullPath: '/contato'
      preLoaderRoute: typeof ContatoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/acessibilidade': {
      id: '/acessibilidade'
      path: '/acessibilidade'
      fullPath: '/acessibilidade'
      preLoaderRoute: typeof AcessibilidadeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/patotas': {
      id: '/app/patotas'
      path: '/patotas'
      fullPath: '/app/patotas'
      preLoaderRoute: typeof AppPatotasRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/mural': {
      id: '/app/mural'
      path: '/mural'
      fullPath: '/app/mural'
      preLoaderRoute: typeof AppMuralRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/membros': {
      id: '/app/membros'
      path: '/membros'
      fullPath: '/app/membros'
      preLoaderRoute: typeof AppMembrosRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/jogos': {
      id: '/app/jogos'
      path: '/jogos'
      fullPath: '/app/jogos'
      preLoaderRoute: typeof AppJogosRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppJogosRoute: typeof AppJogosRoute
  AppMembrosRoute: typeof AppMembrosRoute
  AppMuralRoute: typeof AppMuralRoute
  AppPatotasRoute: typeof AppPatotasRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppJogosRoute: AppJogosRoute,
  AppMembrosRoute: AppMembrosRoute,
  AppMuralRoute: AppMuralRoute,
  AppPatotasRoute: AppPatotasRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AcessibilidadeRoute: AcessibilidadeRoute,
  AppRoute: AppRouteWithChildren,
  ContatoRoute: ContatoRoute,
  MetodologiaRoute: MetodologiaRoute,
  SobreRoute: SobreRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
